/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/*
 * servo_capi.h -- the C ABI of libservo as consumed by Tuuli.
 *
 * This header is Tuuli's *binding contract* with the pinned Servo release
 * (see ../SERVO_TAG).  It mirrors the `servo_capi` crate's exported surface
 * one-to-one and is the ONLY file in the repository that spells servo_*
 * symbols.  Everything above it goes through Tuuli::Engine (src/lib/engine).
 *
 * Rules:
 *  - The header in the libservo-devel RPM (generated by cbindgen from the
 *    pinned tag) is authoritative.  This copy exists so the shim can be
 *    compiled and type-checked on a host without Servo, against the
 *    no-op stub in stub/.  M0 exit criterion: the two headers diff clean
 *    modulo comments.  tools/check-capi-header.sh performs the comparison.
 *  - Anything Tuuli needs that is not here is added upstream in
 *    servo_capi, not by reaching into libservo from Rust glue (spec 3.3).
 *  - Threading (spec 4.2):
 *      * All servo_* calls except servo_webview_paint() and
 *        servo_deinit() are made from the thread that called servo_init()
 *        ("the embedder thread"; Tuuli's Qt GUI thread).
 *      * servo_webview_paint() is called from the thread on which the
 *        rendering context is current (Tuuli's Qt render thread).  The
 *        embedder guarantees no other servo_* call is in flight while it
 *        runs.
 *      * The wake_up callback may be invoked from ANY Servo thread and must
 *        do nothing but post a message to the embedder thread.
 *      * All other callbacks are invoked from inside
 *        servo_spin_event_loop() on the embedder thread.  Tuuli still
 *        marshals them through Qt::QueuedConnection before touching Qt
 *        objects (spec 4.2), so this is a guarantee we do not depend on.
 *  - Coordinates: input goes in as CSS pixels (spec 6.1).  Rects handed
 *    back by callbacks are CSS pixels relative to the webview origin.
 *  - Strings are UTF-8, NUL-terminated, and owned by the callee for the
 *    duration of the call only.  Strings returned by servo_* getters are
 *    freed with servo_string_free().
 */

#ifndef SERVO_CAPI_H
#define SERVO_CAPI_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Versioning ------------------------------------------------------- */

#define SERVO_CAPI_VERSION_MAJOR 0
#define SERVO_CAPI_VERSION_MINOR 5

/* Runtime check that the loaded libservo matches the header we compiled
 * against.  Returns 0 on success, non-zero on mismatch. */
int servo_capi_version_check(uint32_t major, uint32_t minor);
const char* servo_version_string(void); /* e.g. "0.5.0", static storage */

/* ---- Opaque handles --------------------------------------------------- */

typedef struct ServoInstance ServoInstance;
typedef struct ServoWebView ServoWebView;
typedef struct ServoRenderingContext ServoRenderingContext;
typedef struct ServoPermissionRequest ServoPermissionRequest;
typedef struct ServoNavigationRequest ServoNavigationRequest;
typedef struct ServoDownload ServoDownload;
typedef struct ServoSimpleDialog ServoSimpleDialog;

void servo_string_free(char* s);

/* ---- Enums ------------------------------------------------------------ */

typedef enum ServoGlApi {
    SERVO_GL_API_GLES = 0,   /* GLES 3.x; Tuuli reports 3.2 (spec 5.2) */
    SERVO_GL_API_GL = 1
} ServoGlApi;

typedef enum ServoLoadStatus {
    SERVO_LOAD_STARTED = 0,
    SERVO_LOAD_HEAD_PARSED = 1,
    SERVO_LOAD_COMPLETE = 2
} ServoLoadStatus;

typedef enum ServoTouchEventType {
    SERVO_TOUCH_DOWN = 0,
    SERVO_TOUCH_MOVE = 1,
    SERVO_TOUCH_UP = 2,
    SERVO_TOUCH_CANCEL = 3
} ServoTouchEventType;

typedef enum ServoInputType {
    SERVO_INPUT_NONE = 0,
    SERVO_INPUT_TEXT,
    SERVO_INPUT_URL,
    SERVO_INPUT_EMAIL,
    SERVO_INPUT_NUMBER,
    SERVO_INPUT_PASSWORD,
    SERVO_INPUT_TEL,
    SERVO_INPUT_SEARCH,
    SERVO_INPUT_DATE,
    SERVO_INPUT_TIME,
    SERVO_INPUT_DATETIME,
    SERVO_INPUT_MONTH,
    SERVO_INPUT_WEEK,
    SERVO_INPUT_COLOR
} ServoInputType;

typedef enum ServoPermissionKind {
    SERVO_PERMISSION_GEOLOCATION = 0,
    SERVO_PERMISSION_NOTIFICATIONS,
    SERVO_PERMISSION_CAMERA,
    SERVO_PERMISSION_MICROPHONE,
    SERVO_PERMISSION_PERSISTENT_STORAGE,
    SERVO_PERMISSION_MIDI,
    SERVO_PERMISSION_BLUETOOTH,
    SERVO_PERMISSION_CLIPBOARD_READ,
    SERVO_PERMISSION_CLIPBOARD_WRITE
} ServoPermissionKind;

typedef enum ServoKeyState {
    SERVO_KEY_DOWN = 0,
    SERVO_KEY_UP = 1
} ServoKeyState;

typedef enum ServoCompositionState {
    SERVO_COMPOSITION_START = 0,
    SERVO_COMPOSITION_UPDATE = 1,
    SERVO_COMPOSITION_END = 2
} ServoCompositionState;

typedef enum ServoEditingAction {
    SERVO_EDIT_COPY = 0,
    SERVO_EDIT_CUT,
    SERVO_EDIT_PASTE,
    SERVO_EDIT_SELECT_ALL
} ServoEditingAction;

typedef enum ServoSimpleDialogKind {
    SERVO_DIALOG_ALERT = 0,
    SERVO_DIALOG_CONFIRM,
    SERVO_DIALOG_PROMPT
} ServoSimpleDialogKind;

typedef enum ServoMediaSessionEvent {
    SERVO_MEDIA_SESSION_METADATA = 0,
    SERVO_MEDIA_SESSION_PLAYBACK_PLAYING,
    SERVO_MEDIA_SESSION_PLAYBACK_PAUSED,
    SERVO_MEDIA_SESSION_PLAYBACK_NONE,
    SERVO_MEDIA_SESSION_POSITION
} ServoMediaSessionEvent;

typedef enum ServoSiteDataKind {
    SERVO_SITE_DATA_COOKIES = 1 << 0,
    SERVO_SITE_DATA_LOCAL_STORAGE = 1 << 1,
    SERVO_SITE_DATA_SESSION_STORAGE = 1 << 2,
    SERVO_SITE_DATA_HTTP_CACHE = 1 << 3,
    SERVO_SITE_DATA_ALL = 0xFFFF
} ServoSiteDataKind;

typedef enum ServoUserAgentPlatform {
    SERVO_UA_PLATFORM_DESKTOP = 0,
    SERVO_UA_PLATFORM_ANDROID = 1,
    SERVO_UA_PLATFORM_OPENHARMONY = 2,
    SERVO_UA_PLATFORM_MOBILE_LINUX = 3   /* spec 5.4 -- upstream contribution */
} ServoUserAgentPlatform;

/* ---- Plain structs ---------------------------------------------------- */

typedef struct ServoRect {
    float x, y, width, height;         /* CSS px */
} ServoRect;

typedef struct ServoSize {
    uint32_t width, height;            /* device px */
} ServoSize;

typedef struct ServoProxyConfig {
    const char* http;      /* "host:port" or NULL */
    const char* https;
    const char* no_proxy;  /* comma-separated, may be NULL */
    const char* pac_url;   /* may be NULL; proxy auto-config */
} ServoProxyConfig;

/* ---- Rendering context ------------------------------------------------ */

/* Embedder-owned GL context (spec 5.2).  Servo never creates its own EGL
 * context when built this way; it paints into the framebuffer named by
 * framebuffer_object() on the thread where the context is current. */
typedef struct ServoRenderingContextVTable {
    void* user_data;
    bool     (*make_current)(void* ud);              /* no-op for Tuuli */
    void     (*swap_buffers)(void* ud);              /* no-op for Tuuli */
    void     (*size)(void* ud, ServoSize* out);      /* current FBO size */
    void     (*resize)(void* ud, ServoSize size);
    uint32_t (*framebuffer_object)(void* ud);        /* bound FBO id, 0 = default */
    void*    (*get_proc_address)(void* ud, const char* name);
    void     (*prepare_for_rendering)(void* ud);     /* called before paint */
    void     (*present)(void* ud);                   /* called after paint */
} ServoRenderingContextVTable;

ServoRenderingContext* servo_rendering_context_new_external(
    const ServoRenderingContextVTable* vtable, ServoGlApi api,
    uint32_t gl_major, uint32_t gl_minor);
void servo_rendering_context_free(ServoRenderingContext* ctx);

/* ---- Instance --------------------------------------------------------- */

typedef struct ServoInstanceCallbacks {
    void* user_data;
    /* May be called from any thread. Must only post to the embedder thread. */
    void (*wake_up)(void* ud);
    /* Servo hit an unrecoverable internal error.  Embedder thread. */
    void (*panic)(void* ud, const char* reason, const char* backtrace);
    /* Servo wants to open a new top-level webview (window.open, target=_blank).
     * Return a webview created with servo_webview_new_auxiliary(), or NULL. */
    ServoWebView* (*request_create_new_webview)(void* ud, ServoWebView* parent);
    /* System clipboard bridge (spec 8.3).  Synchronous, embedder thread.
     * The returned pointer stays valid until the next clipboard_get_text
     * call. */
    const char* (*clipboard_get_text)(void* ud);
    void (*clipboard_set_text)(void* ud, const char* text);
} ServoInstanceCallbacks;

typedef struct ServoInstanceConfig {
    const char* user_agent;              /* NULL = Servo default for platform */
    ServoUserAgentPlatform ua_platform;  /* engages is_mobile() (spec 5.4) */
    const char* certificate_path;        /* system CA bundle (spec 8.1) */
    const char* config_dir;              /* cookies, storage, cache root */
    const char* cache_dir;
    const ServoProxyConfig* proxy;       /* may be NULL */
    /* Servo preference overrides as "name=value" strings (see docs). */
    const char* const* prefs;
    size_t prefs_count;
    bool enable_hardware_video_decode;   /* gst-droid path (spec 8.2) */
    const char* gst_plugin_path;         /* extra GStreamer plugin dir or NULL */
    uint32_t layout_threads;             /* 0 = auto */
} ServoInstanceConfig;

/* Must be called with the rendering context current on the calling thread
 * (WebRender compiles its shader set here; spec 5.3). */
ServoInstance* servo_init(const ServoInstanceConfig* config,
                          ServoRenderingContext* ctx,
                          const ServoInstanceCallbacks* callbacks);

/* Runs pending Servo work; invokes callbacks.  Returns false once Servo has
 * shut down. */
bool servo_spin_event_loop(ServoInstance* servo);

/* Tears down Servo.  Rendering context must be current. */
void servo_deinit(ServoInstance* servo);

void servo_set_pref(ServoInstance* servo, const char* name, const char* value);
void servo_set_proxy(ServoInstance* servo, const ServoProxyConfig* proxy);

/* SiteDataManager (spec 7.3).  origin == NULL clears everything. */
void servo_clear_site_data(ServoInstance* servo, const char* origin,
                           uint32_t kinds /* ServoSiteDataKind bits */);

/* ---- WebView ---------------------------------------------------------- */

typedef struct ServoWebViewCallbacks {
    void* user_data;
    void (*url_changed)(void* ud, const char* url);
    void (*title_changed)(void* ud, const char* title);
    void (*load_status_changed)(void* ud, ServoLoadStatus status);
    /* RGBA8, row stride == width*4.  Pixels valid for the call only. */
    void (*favicon_changed)(void* ud, const uint8_t* rgba, uint32_t w, uint32_t h);
    void (*history_changed)(void* ud, const char* const* urls, size_t count,
                            size_t current);
    void (*new_frame_ready)(void* ud);
    void (*status_text_changed)(void* ud, const char* text);
    void (*cursor_changed)(void* ud, const char* css_cursor_name);
    void (*fullscreen_state_changed)(void* ud, bool fullscreen);
    /* Root scroll offset, pinch zoom and content size (CSS px): session
     * persistence and the pulley-menu handoff at content edges (spec 6.2). */
    void (*viewport_changed)(void* ud, float scroll_x, float scroll_y,
                             float pinch_zoom, float content_width,
                             float content_height);

    /* IME (spec 6.3). rect is the caret/element rect in CSS px. */
    void (*show_ime)(void* ud, ServoInputType type, const char* text,
                     bool multiline, ServoRect rect);
    void (*hide_ime)(void* ud);
    void (*ime_selection_changed)(void* ud, const char* text,
                                  uint32_t cursor, uint32_t anchor);

    /* Async requests.  The request object stays valid until the embedder
     * calls the matching servo_*_allow/deny/… function exactly once. */
    void (*request_permission)(void* ud, ServoPermissionRequest* req);
    void (*request_navigation)(void* ud, ServoNavigationRequest* req);
    void (*show_simple_dialog)(void* ud, ServoSimpleDialog* dialog);

    /* Hit-test result for servo_webview_request_context_menu(), or a
     * right-click / contextmenu event from content (spec 6.2). */
    void (*show_context_menu)(void* ud, float css_x, float css_y,
                              const char* link_url, const char* image_url,
                              const char* selected_text, bool editable);

    /* Downloads.  Servo performs the transfer; the embedder chooses the
     * destination with servo_download_accept(). */
    void (*download_requested)(void* ud, ServoDownload* download,
                               const char* url, const char* suggested_name,
                               const char* mime_type, int64_t total_bytes);
    void (*download_progress)(void* ud, ServoDownload* download,
                              int64_t received, int64_t total);
    void (*download_finished)(void* ud, ServoDownload* download, bool ok,
                              const char* error);

    void (*media_session_event)(void* ud, ServoMediaSessionEvent event,
                                const char* title, const char* artist,
                                const char* album, double position_s,
                                double duration_s);
    void (*notification_requested)(void* ud, const char* title,
                                   const char* body, const char* icon_url);
    void (*closed)(void* ud);
} ServoWebViewCallbacks;

ServoWebView* servo_webview_new(ServoInstance* servo, ServoRenderingContext* ctx,
                                const ServoWebViewCallbacks* callbacks,
                                bool private_browsing, float hidpi_scale_factor,
                                ServoSize size);
ServoWebView* servo_webview_new_auxiliary(ServoInstance* servo, ServoWebView* parent,
                                          const ServoWebViewCallbacks* callbacks);
void servo_webview_close(ServoWebView* wv);
bool servo_webview_is_private(const ServoWebView* wv);

void servo_webview_load(ServoWebView* wv, const char* url);
void servo_webview_reload(ServoWebView* wv);
void servo_webview_stop(ServoWebView* wv);
void servo_webview_go_back(ServoWebView* wv, uint32_t amount);
void servo_webview_go_forward(ServoWebView* wv, uint32_t amount);

/* Getters return malloc'd strings; free with servo_string_free(). NULL if none. */
char* servo_webview_url(const ServoWebView* wv);
char* servo_webview_title(const ServoWebView* wv);
ServoLoadStatus servo_webview_load_status(const ServoWebView* wv);

void servo_webview_show(ServoWebView* wv, bool raise_to_top);
void servo_webview_hide(ServoWebView* wv);
void servo_webview_focus(ServoWebView* wv);
void servo_webview_blur(ServoWebView* wv);

void servo_webview_resize(ServoWebView* wv, ServoSize size);
/* Visible viewport inside the surface (VKB avoidance, spec 6.3), device px. */
void servo_webview_set_viewport_rect(ServoWebView* wv, uint32_t x, uint32_t y,
                                     uint32_t width, uint32_t height);
void servo_webview_set_hidpi_scale_factor(ServoWebView* wv, float factor);
void servo_webview_set_pinch_zoom(ServoWebView* wv, float zoom);
void servo_webview_set_page_zoom(ServoWebView* wv, float zoom);
void servo_webview_reset_zoom(ServoWebView* wv);
void servo_webview_scroll_to(ServoWebView* wv, float css_x, float css_y);

/* Returns true if a frame was painted into the rendering context's FBO. */
bool servo_webview_paint(ServoWebView* wv);

/* Input.  Points in CSS px relative to the webview origin. */
void servo_webview_touch(ServoWebView* wv, ServoTouchEventType type, int32_t id,
                         float css_x, float css_y);
/* key: W3C KeyboardEvent.key string ("a", "Enter", "Backspace"...);
 * modifiers: bit 0 shift, 1 ctrl, 2 alt, 3 meta. */
void servo_webview_key(ServoWebView* wv, ServoKeyState state, const char* key,
                       uint32_t modifiers);
void servo_webview_ime_composition(ServoWebView* wv, ServoCompositionState state,
                                   const char* text);
void servo_webview_ime_dismissed(ServoWebView* wv);
void servo_webview_editing_action(ServoWebView* wv, ServoEditingAction action);

/* Ask for a hit test at the given CSS point; the result arrives through the
 * show_context_menu callback.  Tuuli detects the long-press itself (spec
 * 6.2) and only uses Servo to find the target. */
void servo_webview_request_context_menu(ServoWebView* wv, float css_x, float css_y);

/* Find in page. */
void servo_webview_find(ServoWebView* wv, const char* text, bool case_sensitive);
void servo_webview_find_next(ServoWebView* wv, bool forward);
void servo_webview_find_clear(ServoWebView* wv);

/* User stylesheets / scripts (spec 9.3).  id is embedder-chosen. */
void servo_webview_add_user_stylesheet(ServoWebView* wv, const char* id,
                                       const char* css);
void servo_webview_remove_user_stylesheet(ServoWebView* wv, const char* id);
void servo_webview_add_user_script(ServoWebView* wv, const char* id,
                                   const char* js);
void servo_webview_remove_user_script(ServoWebView* wv, const char* id);

/* Per-webview UA override (desktop-mode toggle, spec 7.2).  NULL resets. */
void servo_webview_set_user_agent(ServoWebView* wv, const char* ua);

typedef void (*ServoJsResultCallback)(void* ud, bool ok, const char* json_or_error);
void servo_webview_evaluate_javascript(ServoWebView* wv, const char* script,
                                       ServoJsResultCallback cb, void* ud);

/* Screenshot of the current frame, RGBA8.  Caller frees with servo_pixels_free. */
uint8_t* servo_webview_capture(ServoWebView* wv, uint32_t* w, uint32_t* h);
void servo_pixels_free(uint8_t* pixels);

/* ---- Async request objects ------------------------------------------- */

ServoPermissionKind servo_permission_request_kind(const ServoPermissionRequest* r);
const char* servo_permission_request_origin(const ServoPermissionRequest* r);
void servo_permission_request_allow(ServoPermissionRequest* r);
void servo_permission_request_deny(ServoPermissionRequest* r);

const char* servo_navigation_request_url(const ServoNavigationRequest* r);
void servo_navigation_request_allow(ServoNavigationRequest* r);
void servo_navigation_request_deny(ServoNavigationRequest* r);

ServoSimpleDialogKind servo_simple_dialog_kind(const ServoSimpleDialog* d);
const char* servo_simple_dialog_message(const ServoSimpleDialog* d);
const char* servo_simple_dialog_default_value(const ServoSimpleDialog* d);
void servo_simple_dialog_accept(ServoSimpleDialog* d, const char* prompt_value);
void servo_simple_dialog_dismiss(ServoSimpleDialog* d);

void servo_download_accept(ServoDownload* d, const char* destination_path);
void servo_download_reject(ServoDownload* d);
void servo_download_cancel(ServoDownload* d);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* SERVO_CAPI_H */
